{% set name = "innerscope" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/innerscope-{{ version }}.tar.gz
  sha256: ecea67a1aeb302e4139f0da0e70e72be9611a9a71c69c5b390e8db6c2bc2fb1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - toolz

test:
  imports:
    - innerscope
    - innerscope.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eriknw/innerscope
  summary: Expose the inner scope of functions
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/eriknw/innerscope

extra:
  recipe-maintainers:
    - eriknw
