{% set name = "innerscope" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/innerscope-{{ version }}.tar.gz
  sha256: f5423410867360a1d00f6533c55a4af0a2e050d43b424394e51c59b28db2ef4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - toolz

test:
  imports:
    - innerscope
    - innerscope.tests
  commands:
    - pip check
    - pytest -v --pyargs innerscope
  requires:
    - pip
    - pytest

about:
  home: https://github.com/eriknw/innerscope
  summary: Expose the inner scope of functions
  description: |
    Innerscope exposes the inner scope of functions and offers primitives suitable for creating pipelines.
    It explores a design space around functions, dictionaries, and classes.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/eriknw/innerscope

extra:
  recipe-maintainers:
    - eriknw
